ROLE_HEAD_ADMIN = "head_admin"
ROLE_ADMIN = "admin"
ROLE_MANAGER = "manager"
ROLE_EDITOR = "editor"
ROLE_READER = "reader"

ADMIN_ROLES = (ROLE_HEAD_ADMIN, ROLE_ADMIN)
SCHEMA_WRITE_ROLES = (ROLE_HEAD_ADMIN, ROLE_ADMIN, ROLE_MANAGER)
ENTRY_WRITE_ROLES = (ROLE_HEAD_ADMIN, ROLE_ADMIN, ROLE_MANAGER, ROLE_EDITOR)
READ_ROLES = (ROLE_HEAD_ADMIN, ROLE_ADMIN, ROLE_MANAGER, ROLE_EDITOR, ROLE_READER)

ADMIN_ROLE_SET = set(ADMIN_ROLES)
