ROLE_HEAD_ADMIN = "head_admin"
ROLE_ADMIN = "admin"
ROLE_EDITOR = "editor"
ROLE_USER = "user"

ADMIN_ROLES = (ROLE_HEAD_ADMIN, ROLE_ADMIN)
EDITOR_ROLES = (ROLE_HEAD_ADMIN, ROLE_ADMIN, ROLE_EDITOR)
READ_ROLES = (ROLE_HEAD_ADMIN, ROLE_ADMIN, ROLE_EDITOR, ROLE_USER)

ADMIN_ROLE_SET = set(ADMIN_ROLES)
